(global-set-key (kbd "C-w") 'backward-kill-word)
;;(global-set-key (kbd "C-c p s") 'helm-do-ag-project-root)
(global-set-key (kbd "C-c C-r") 'counsel-recentf)
(global-set-key (kbd "C-c g") 'magit-status)
(global-set-key (kbd "C-c l") 'org-store-link)
(global-set-key (kbd "M-o") 'ace-window)
(provide 'init-keybindings)
