(global-set-key (kbd "C-w") 'backward-kill-word)
(global-set-key (kbd "C-c p s") 'helm-do-ag-project-root)
(global-set-key (kbd "C-c C-r") 'counsel-recentf)
(global-set-key (kbd "C-c g") 'magit-status)
(provide 'init-keybindings)
